### ISSUE TITLE
Private cidr to get 3 /27 subnets 

### ISSUE THREAD

**Issue by mg03** [cloudposse/terraform-aws-multi-az-subnets#19]
Is there a way to provide the cidr range so that i can get 3 /27 subnets in the a, b and c azs in us-east-1

Im trying to get 10.51.254.(0/27,  16/27 and 32/27) . as the three subnets

**Comment by Gowiem** [comment]
@mg03 this seems more like a help request then a feature or bug request. I'm sure you've already dealt with this since it's over 2 years old, but please be sure to ask any questions like this in the #terraform channel in http://slack.sweetops.com/ next time around and I'm sure you'll get plenty of help. Closing out.
